theme: jekyll-theme-minimal
root: /
# i just write some stuff to try to push it LOL
# i just write some stuff to try to push it LOL
# i just write some stuff to try to push it LOL
# i just write some stuff to try to push it LOL